server:
  port: 10725
  max-http-header-size: 1024000
spring:
  datasource:
    name: oracle
    url: jdbc:mysql://127.0.0.1:13307/sync_data?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root123456
    driver-class-name: oracle.jdbc.driver.OracleDriver

